# Marco Teórico

## Democracia delegativa

El concepto de democracia delegativa fue acuñado por el sociólogo argentino Guillermo O'Donnell para describir la situación institucional de las nuevas democracias latinoamericanas surgidas tras el fin de los regímenes autoritarios en la región durante las décadas de 1980 y 1990. Esta forma de democracia se basa en la premisa de que el ganador de las elecciones presidenciales tiene derecho a gobernar sin restricciones, considerándose la encarnación del país y el principal defensor de sus intereses [@odonnell1994].

Aunque el concepto se puede relacionar con la idea de populismo, sería incorrecto equipararlos. La principal diferencia entre ambos radica en que la democracia delegativa no pone el mismo énfasis en la construcción de un pueblo que se opone de manera homogénea a una élite o a un enemigo externo [@diaz2023; @peruzzotti2008]. En cambio, la democracia delegativa debe entenderse como una forma de ejercer el poder en contextos democráticos donde prevalece la rendición de cuentas vertical sobre la horizontal [@toppi2018].

La rendición de cuentas vertical se refiere al control periódico de las autoridades frente a los ciudadanos, principalmente mediante las elecciones. La rendición de cuentas horizontal, en cambio, se entiende como el control entre instituciones, poderes del Estado y organismos autónomos [@odonnell1994]. De tal modo, en una democracia delegativa, el líder debe tomar decisiones y cumplir sus promesas de forma eficaz, sin estar sujeto a controles institucionales [@toppi2018]. Mientras que una democracia representativa cuenta con ambas formas de rendición de cuentas, en una democracia delegativa los controles verticales cobran mayor importancia que los horizontales.

A pesar de que Chile normalmente no es considerado como una democracia delegativa, dada la fortaleza de sus instituciones democráticas tras el fin de la Dictadura  [@carlin2018; @odonnell1994], existe evidencia que sugiere que una parte de la población muestra preferencia por esta variedad de democracia  [@carlin2011; @carlin2018]. Según Carlin [-@carlin2018], las personas que apoyan una democracia delegativa en Chile se caracterizan por apoyar a líderes fuertes que unan al país y lo guíen en tiempos de crisis, mostrar orientaciones no-liberales (*iliberals*) hacia los derechos políticos y falta de compromiso hacia los derechos humanos. Sin embargo, este perfil sigue prefiriendo la democracia sobre otras formas de gobierno.

Los liderazgos fuertes, de esta manera, se constituyen como una de las dimensiones fundamentales de las democracias delegativas. Subyace aquí la idea de una nación concebida como un ser orgánico. El Presidente o el líder se transforma, por lo tanto, en una especie de cabeza del Leviatán, cuya función es "sanar la nación uniendo sus fragmentos dispersos en un todo armonioso" [@odonnell1994, p.60].

De lo anterior, se desprende un segunda característica esencial de esta variante de democracia. El líder, para cumplir su cometido, debe saber combinar elementos emocionales y carismáticos con otros altamente técnicos, precisamente bajo la justificación de "sanar" a la nación [@odonnell1994]. Esta impronta tecnocrática mezclada con elementos emocionales no es del todo desconocida en Chile, como se observa en el tipo ideal portaliano [@araujo2013], una forma sociohistórica de ejercicio de la autoridad en el país. Por otro lado, podría también recordar a la discusión sobre el surgimiento de actitudes tecnocráticas y tecnopopulistas en países europeos y su relación, muchas veces contradictoria, con la democracia [@chiru2022; @ganuza2020; @pilet2023].

Por lo tanto, se entenderá que el respaldo a la democracia delegativa implica el apoyo a líderes fuertes que tengan la capacidad para satisfacer eficazmente las demandas ciudadanas,  incluso si esto conlleva pasar por encima de otras instancias de control institucional, combinando elementos carismáticos con enfoques altamente tecnocráticos.

O'Donnell [-@odonnell1994] argumenta que a la democracia delegativa subayace un individualismo extremo, donde los ciudadanos deben actuar de manera independiente de sus identidades y afiliaciones para elegir al *individuo* más adecuado para asumir la responsabilidad de la nación. Esta idea puede parecer contradictoria con la noción que ha sido aceptada, desde Tocqueville en adelante, de un estrecho vínculo entre el individualismo y las variantes más liberales y representativas de democracia. Al fin y al cabo, la democracia liberal se basa en la libre asociación de individuos soberanos capaces de otorgar legitimidad al orden social [@martuccelli2010]. Si a esta contradicción se le añade la evidencia empírica que apunta a la asociación entre el individualismo con el conservadurismo [@zhang2009] y el autoritarismo [@kemmelmeier2003], la dominancia social [@strunk1999], el panorama general sugiere que la relación entre individualismo y democracia está lejos de ser unívoca.

Frente a lo anterior, y con el objetivo de explorar posibles divergencias en la asociación entre los dos fenómenos principales abordados en esta investigación, la siguiente sección se enfocará en una revisión crítica de la conceptualización que, desde la psicología cultural, se ha realizado sobre individualismo y colectivismo. Tras eso, se presentará la propuesta teórica que se asumirá en la investigación, la que se encuentra fundamentada en la teoría de la individualización y en la sociología del individuo.

## Individualismo

### Individualismo-Colectivismo desde la psicología cultural

El fenómeno del individualismo ha sido principalmente investigado desde la psicología cultural, con un enfoque especial en la comparación entre distintas culturas. La mayoría de las veces, se explora en contraposición al colectivismo. Desde esta perspectiva, de tal modo, se tienden a categorizar culturas (y, se debe notar, cultura se entiende casi siempre como sinónimo de país), ya sea como individualistas o como colectivistas.

Para Hofstede, individualismo y colectivismo representan los polos opuestos de un continuo unidimensional que permite distinguir entre culturas individualistas y culturas colectivistas [@yoon2010]. Las sociedades individualistas se caracterizarían por lazos poco estrechos entre individuos, de quienes se espera se hagan cargo de sí mismos y de su familia inmediata. Las sociedades colectivistas, en tanto, se definen porque sus miembros están integrados desde su nacimiento a grupos fuertemente cohesionados que los protegen a lo largo de sus vidas a cambio de una lealtad incuestionable [@yoon2010]. A pesar de que Hofstede mismo advierte que estas definiciones son aplicables a nivel cultural y no en el individual, y que representan procesos dinámicos en los que las culturas pueden transformarse, estas recomendaciones no siempre han sido seguidas por los investigadores que han adoptado esta perspectiva.

Frente a esto, se han realizado esfuerzos para desarrollar conceptualizaciones alternativas, siendo una de las más populares la del *self-construal* [@cross2011]. *Self-construal*, que puede traducirse al español como autoconstrucción o autoconcepción, se refiere a las formas en que el individuo se concibe a sí mismo, ya sea de forma independiente o interdependiente de sus grupos. Esta propuesta se diferencia de la de Hofstede en que es un constructo bidimensional, donde un eje representa al individualismo y otro al colectivismo. Sin embargo, a pesar de que se ha enfatizado que el *self-construal* y el individualismo-colectivismo son fenómenos distintos, su operacionalizaciones a menudo se superponen [@cross2011]. Además, persiste una interpretación más o menos explícita que relaciona concepciones independientes con culturas individualistas [@cross2011; @voronov2002].

Por otro lado, el uso de individualismo-colectivismo ha sido criticado por su falta de claridad conceptual, calificándolo como un concepto *catch-all*, que se utiliza por defecto para explicar diferencias culturales [@voronov2002]. Subyace aquí una dimensión normativa: El individualismo se ha entendido como una característica esencial de la cultura estadounidense y anglosajona, y se asocia constantemente a la modernidad y al desarrollo [@voronov2002; @wang2010; @martuccelli2010]. Individualismo, así, suele tener una connotación positiva; colectivismo, una negativa [@moemeka1998], sobre todo en Estados Unidos y otros países anglosajones. En este sentido, no es sorprendente que individualismo y colectivismo puedan evocar a algunas de las distinciones establecidas por la sociología clásica: sociedad mecánica-sociedad orgánica; sociedad tradicional-sociedad moderna; o comunidad-sociedad.

La falta de claridad conceptual se evidencia en el metaestudio realizado por Oyserman y sus colegas [-@oyserman2002]. A través de un análisis de contenido a las escalas más utilizadas para medir estos fenómenos, descubrieron que individualismo puede referirse a hasta 6 cosas distintas (independencia, orientación al logro, competencia, unicidad, autoconocimiento y comunicación directa); mientras que colectivismo a otras 8 (relaciones, pertenencia, deber, armonía, búsqueda de consejo, contextualidad, jerarquía y grupos).

Brewer y Chen [-@brewer2007] llevaron este análisis un paso más allá al señalar que no existe una verdadera simetría en la forma en que se operacionalizan el individualismo y el colectivismo. Mientras que los ítems utilizados para medir el individualismo suelen centrarse en la identidad y la agencia de los individuos, el colectivismo se suele medir como un sistema de valores.

También se ha puesto atención a la falta de claridad de quiénes son los colectivos del colectivismo, sin establecer una distinción clara entre grupos, colectivos y comunidades. Un ejemplo de esta indefinición es el problema del familiarismo: La familia, de alguna forma u otra, se ha integrado en las definiciones y operacionalizaciones tanto de individualismo[^1] como de colectivismo [@oyserman2002].

Moemeka [-@moemeka1998] sostiene que los colectivos se forman por elección mientras que las comunidades son preexistentes a las personas. Bajo este punto de vista, no hay verdadera contradicción entre colectivismo e individualismo. Por ejemplo, los partidos políticos y movimientos sociales -- en fin, la sociedad civil entendida como el libre juego de los intereses individuales y privados [@arribas1999] -- tienen típicamente un mayor desarrollo en sociedades denominadas como individualistas.

Frente a lo anterior, Moemeka [-@moemeka1998] sugiere que en lugar de hablar de colectivismo, se debería utilizar el concepto de comunalismo. Sin embargo, Brewer y Chen [-@brewer2007], mediante un metaanálisis, concluyen que las escalas más utilizadas no miden realmente comunidades, según lo definido por Moemeka, sino que se centran en las relaciones interpersonales. Por ello, proponen distinguir esta dimensión de la colectiva propiamente tal, que se referiría más bien a grupos enteros, sean de carácter étnico, religioso o nacional.

Estas discrepancias conceptuales podrían explicar las "anomalías" observadas en varios de estos estudios, como que los individualistas pueden ser tanto o más colectivistas que los colectivistas mismos [@oyserman2002], o que en determinados contextos los colectivistas actúan de manera individualista [@voronov2002]. A nivel agregado, Chile podría considerarse como un claro ejemplo de estas contradicciones:

Bajo la definición de Hofstede, la sociedad chilena ha sido clasificada como colectivista [@rojas2008]. Esto concuerda con observaciones que han señalado que el colectivismo en Chile es alto, tanto si se mide como el opuesto al individualismo [@oyserman2002] o entendido como un *self-construal* interdependiente [@benavides2020]. No obstante, también es cierto que los niveles de individualismo observados en el país llegan a ser incluso más altos que aquellos obtenidos en Estados Unidos [@oyserman2002] o Noruega [@kolstad2009].

Esto abre la pregunta de si Chile realmente es una sociedad colectivista, y si no lo es, ¿hasta qué punto es una sociedad individualista? Responder esta pregunta implica el riesgo de salir de un relato de insuficiencia ("Chile no es un país individualista"), solo para caer en un relato del *ni, ni* [@martuccelli2010]: "Chile no es *ni* individualista *ni* colectivista".

La teoría social avanza, siguiendo una clásica argumentación parsoniana [@bouzanis2019], mediante la formulación de conceptos positivos que permitan superar las categorías residuales de un sistema teórico. Al estudiar fenómenos como el individualismo en Chile sería fácil caer en esta ambigüedad, pues su realidad no se ajusta claramente a las categorías positivas de la perspectiva hasta aquí revisada [@bouzanis2019]. Si una cultura no es ni colectivista ni individualista, surge la pregunta, ¿qué es exactamente? La incapacidad de responder esta pregunta representa una limitación significativa en el esfuerzo de describir sociológicamente la sociedad chilena. Como mínimo, la tarea de los científicos sociales debería ser la de poder nombrar a nuestras sociedades.

Para escapar de esta trampa es necesario dar un giro hacia una perspectiva teórica que provea el lenguaje para describir el individualismo chileno como algo más que una simple categoría residual. Como se argumentará en la siguiente sección, la sociología del individuo podría servir como la principal vía para llevar a cabo este ejercicio.

### Individualismo desde la Sociología del Individuo

Es importante resaltar que en la literatura revisada en la sección anterior no se encontraron referencias a la teoría de la individualización. En este contexto, se plantea que esta tradición teórica puede proporcionar elementos fundamentales para comprender el fenómeno del individualismo en Chile. En efecto, la individualización puede ser entendida como una forma de individualismo institucionalizado. Esto es, como un proceso social en que "las instituciones cardinales de la sociedad moderna -- los derechos civiles, políticos y sociales básicos, pero también el empleo remunerado y la formación y movilidad que éste conlleva -- están orientados al individuo y no al grupo" [@beck2003, p. 32].

De forma sucinta, la teoría de la individualización surgió en Europa a mediados de la década de 1980 con el propósito de explicar las trasformaciones aparejadas a lo que se ha denominado como *modernidad reflexiva*. Esta teoría sostiene que se está produciendo un proceso de distanciamiento entre la agencia y la estructura, dejando a un individuo cada vez más responsable de sí mismo y de dar respuesta por sus propios medios a las incertidumbres producidas en el mundo social [@beck2003]. Desde fines de los años 90, está teoría ha sido uno de los marcos analíticos preferidos por las ciencias sociales en Chile para dar cuenta de las transformaciones culturales, sociales y económicas producidas en el país durante las últimas décadas [@yopo2013].

En el marco de este enfoque, el marco analítico de esta investigación se sustenta principalmente en la sociología del individuo desarrollada por Danilo Martuccelli. Desde este enfoque, tanto en su obra individual [@martuccelli2010; @martuccelli2018], como en colaboración con Kathya Araujo [@araujo2014; @araujo2020; @araujo2012], Martuccelli ha hecho esfuerzos contundentes para describir la forma particular del individualismo en Chile y América Latina. Si en la sección anterior se mostró la ambigüedad con que se definen los colectivos del colectivismo, a partir del trabajo de Martuccelli es posible revelar la noción de individuo que subyace a las conceptualizaciones imperantes de individualismo.

Martuccelli [-@martuccelli2010] argumenta que la representación del individuo que se volvió hegemónica para la modernidad es un individuo que es soberano en al menos dos acepciones. En primer lugar, porque se espera de este que sea dueño de sí mismo, de manera independiente, autónoma y singular. En segundo lugar, porque es un ente racional capaz de legitimar el orden social y la soberanía colectiva.

Este individuo se encuentra en el vértice de un modelo de representación de la vida social que lo sitúa en el centro del pacto social [@martuccelli2010; @martuccelli2018]. Este modelo es lo que comúnmente se entiende como individualismo. Un individualismo institucional, precisa Martuccelli [-@martuccelli2018] que se caracteriza por 3 rasgos fundamentales:

-   Una separación radical entre holismo e individualismo
-   Una concepción atomizada del individuo. Es decir, la idea de que los individuos son prexistentes de sus lazos sociales.
-   La preeminencia del rol de las instituciones en los procesos de individuación, de modo que la individualidad deja de ser percibida como una desviación y se convierte en el modelo institucional a encarnar.

Las divergencias respecto a este modelo, observadas en otras regiones del mundo, a menudo ha llevado de la negación existencia de individuos, individualización e individualismo en éstas [@martuccelli2010]. Como se mencionó anteriormente, subyace aquí un aspecto normativo que asocia al individualismo y al individuo soberano con el orden social de la modernidad occidental, mientras que relaciona a la sociedad tradicional con todas sus desviaciones [@martuccelli2018].

Abordar el fenómeno del individualismo desde la sociología del individuo presenta la ventaja de que permite desembarazarse de esta conceptualización unívoca de individuo. Además, proporciona una salida a las definiciones múltiples y ambiguas de colectivismo, expuestas en la sección anterior. Frente a ello, se propone una definición que permita teorizar el fenómeno para la sociedad chilena.

Se entenderá así como individualismo a los modelos de representación de la vida social que definen el rol del individuo en la sociedad. Bajo tales modelos, los individuos deben hacerse cargo de sus propias vidas en condiciones diversas de legitimidad de la acción individual, distintas representaciones culturales y autoconcepciones del individuo, y diferentes valores e imperativos estructuralmente producidos.

A continuación, pues, se profundizará en la propuesta teórica que aquí se está planteando, examinando más en detalle las dimensiones que se desprenden de esta. 

#### Legitimidad de la acción individual

Está dimensión hace referencia a las creencias sobre la agencia de los individuos en el mundo social [@brewer2007] y la legitimidad de acciones individualizadas en las esferas de la economía, la política y las emociones [@cortois2018]. Una mayor legitimidad de la acción individual se relaciona a una mayor valoración de la individualidad, la cual se define como el "grado de diferenciación o de singularización reconocido o legítimamente alcanzado por un individuo dentro de un colectivo" [@martuccelli2018, p. 10].

Bajo el modelo del individualismo institucional, la individualidad deja de ser una anomalía para pasar a ostentar altos niveles de legitimidad [@martuccelli2018]. Sin embargo, esto se vería tensionado, por ejemplo, por la acentuación de conductas individualizadas sin ruptura de lazos comunitarios en sociedad africanas, modelo que Martuccelli [-@martuccelli2018] denomina como individualismo comunitario. Más cercano a la realidad nacional, Araujo y Martuccelli [-@araujo2020a] constatan que la individualidad ha sido históricamente vista con sospecha en sociedades latinoamericanas.

Ahora bien, se debe resaltar que el individualismo ha sido institucionalizado principalmente en 3 esferas: la económica, la política y la afectiva [@cortois2018; @martuccelli2018]. Esto se refleja en la existencia de 3 guiones para el individualismo institucional; en la esfera económica, un individualismo utilitario; en la política, un individualismo moral; y en la afectiva, un individualismo expresivo [@cortois2018]. 

Es crucial hacer esta distinción, ya que en una misma sociedad es posible encontrar grupos e individuos que legitimen el individualismo en algunas esferas pero no en otras. Por ejemplo, en América del Norte se ha observado que grupos conservadores apoyan la autodeterminación individual en la economía y en la elección de escuelas, pero no necesariamente en lo que respecta al derecho al aborto o a la eutanasia [@kemmelmeier2003].

El individualismo utilitario se caracteriza por concebir al individuo como propietario de su vida y sus habilidades, las que son susceptibles a ser intercambiadas en el libre mercado. La acción se entiende aquí como estratégica, es decir, como medios para conseguir fines individuales. De tal modo, el Otro no tiene un valor intrínseco, sino que se considera como un medio para tales fines [@cortois2018]. 

En el contexto chileno, este tipo de individualismo podría vincularse a la instauración del neoliberalismo y la emergencia de un *homo neoliberalis*, principalmente mediante el acceso al consumo [@araujo2012; @araujo2020a]. Sin embargo, su legitimidad está lejos de ser univoca, como se evidencia en la relación ambigua de los chilenos frente al oportunismo [@araujo2014] y al consumismo [@araujo2012].

El individualismo moral, por otro lado, enfatiza la obligación moral de tratar al Otro como un fin en sí mismo. La institucionalización de esta idea se refleja en las declaraciones de derechos humanos, civiles y sociales, que reconocen a los individuos como iguales y autónomos [@cortois2018]. En América Latina, este tipo de individualismo ha experimentado una importante valorización tras las dictaduras del siglo XX [@araujo2020a]. En Chile, además, se puede observar en las aspiraciones por la democratización y la horizontalización de lazo social, así como en las demandas por dignidad [@araujo2012].

Si cada una de estas variantes introducidas se puede relacionar con las dos vertientes de la *doble revolución* descrita por Eric Hobsbawm, Eva Illouz [-@illouz2020] introduce una tercera revolución acontecida en el plano emocional y en la esfera privada. Se trata de un cambio cultural del que emerge el individualismo expresivo, en el que la acción social se entiende como un medio para la expresión auténtica del yo [@cortois2018]. Opera, así, en el ámbito del amor, la sexualidad, la identidad, la intimidad y la familia.

El individualismo expresivo se diferencia del individualismo utilitario en que, aunque ambos están dirigidos hacia el propio individuo, el expresivo carece del carácter instrumental y estratégico del utilitarismo. Aunque, en ese sentido, podría parecerse al individualismo moral, la diferencia fundamental radica en que, mientras el moral enfatiza la igualdad entre los individuos, el individualismo expresivo otorga mayor importancia a la diferencia, valorando la autenticidad y la unicidad.

#### (Auto)concepciones del individuo:

Esta dimensión aborda las diversas concepciones en torno a las que se pueden definir las identidades de los individuos en relación a sus grupos de referencia [@brewer2007].

La concepción independiente es aquella en que el individuo se concibe como un ente atomizado y prexistente a sus lazos sociales. Aunque esta concepción se ha considerado como propia de las culturas individualistas [@benavides2020; @cross2011], tal idea ha sido problematizada teórica [@voronov2002] y empíricamente [@benavides2020; @kolstad2009]. Además, la persistencia de los llamados valores asiáticos en esas sociedades, que conceptualizan al individuo como inseparable de sus lazos sociales [@zhai2022], y la conceptualización de un híper-actor relacional en la sociedad chilena [@araujo2020], sugieren la posibilidad de individualismos que difieren de las concepciones independientes. 

De tal modo, se podrían identificar, además, concepciones relacionales y concepciones colectivas [@brewer2007]. En las primeras, la identidad del individuo se define por sus relaciones cercanas, tales como la familia o los amigos. En las segundas, en tanto, es la pertenencia a colectivos sociales más abstractos -- esto es, grupos nacionales, regionales, étnicos o religiosos -- lo que define a la identidad individual [@brewer2007]

#### Valores e Imperativos:

Esta dimensión se refiere a la importancia relativa que se le otorga en una sociedad a diversos valores e imperativos individuales o colectivos [@brewer2007], los cuales son producidos por procesos sociohistóricos de individuación [@martuccelli2018]. En el contexto del individualismo institucional, el principal valor para el individuo es la autonomía [@martuccelli2010]. Esto se promueve a través de un entramado institucional [@martuccelli2018] que promueve que los individuos se constituyen a sí mismos, planifique su propia vida y acepten la responsabilidad si fracasan [@robles2001]. Es, pues, una individuación reflexiva en la que los individuos se definen por el imperativo de ejercer control de sus destinos y tomar decisiones de manera autónoma [@silvapalacios2015]. Por lo tanto, su imperativo principal es "vive tu vida como quieras" [@robles2001].

Sin embargo, también se han planteado visiones críticas a esta concepción, particularmente desde América Latina [@araujo2012; @robles2001]. No toda individuación sería reflexiva, ya que muchos individuos podrían experimentarla de forma delegativa, como una imposición [@silvapalacios2015]; no como un mundo de posibilidades, sino como uno lleno de incertidumbres. Los individuos, de tal modo, deben enfrentar las inseguridades ontológicas de la vida social a partir de sus propias habilidades bajo el imperativo de "arréglatelas como puedas" [@araujo2014; @robles2001]. Frente a esto, la valorización de la autonomía se desplaza por la búsqueda de seguridad como valor principal de esta forma de individuación [@silvapalacios2015]

### Perfiles de Individualismo y democracia delegativa

Bajo este marco analítico, el colectivismo puede entenderse como un conjunto de modalidades de individualismo que son características de sociedades donde la acción individual puede estar menos legitimada, o en que los individuos construyen su identidad en torno a la pertenencia a una colectividad, o en que la autonomía no se constituye como el principal valor en torno a los que se definen los individuos. En ningún caso, sería incompatible con la idea de individualismo, pues estas colectividades son grupos de libre elección [^2] conformadas por individuos que persiguen objetivos individuales a través de la acción colectiva [@arribas1999; @moemeka1998]. Zygmunt Bauman teorizó en este sentido, argumentando que los movimientos de trabajadores durante los siglos XIX y XX son resultado de procesos de individualización desiguales en esas sociedades:

> Las personas con menos recursos, y por tanto con menos elección, tenían que compensar esta carencia individual con la fuerza de los números, es decir, cerrando filas y participando en acciones colectivas. Como ha dicho Claus Offe, la acción colectiva y orientada a la clase llegó a los que estaban en la parte baja de la escala social de manera tan *natural* y *obvia* como llegaba a sus jefes y empresarios la búsqueda individual de las metas vitales" [@bauman2003, p. 23].

En la argumentación de Bauman, ya se puede divisar un punto clave en este marco analítico: El individualismo institucional es solo una modalidad entre varias. El propio Martuccelli [-@martuccelli2018] esquematiza una descripción de diversas variantes de individualismo que serían propias de las sociedades africanas (el individualismo comunitario), asiáticas (el individualismo ontorrelacional) y latinoamericanas (el individualismo agéntico). Pero, una lectura aún más interesante del pasaje citado es que permite vislumbrar las difracciones dentro de una misma sociedad, y que esto es así incluso en las sociedades industriales en que emergió el modelo del individualismo institucional: El individualismo de los burgueses no era el mismo que el individualismo de los obreros.

Las diferencias raciales en las escalas de individualismo-colectivismo en Estados Unidos [@oyserman2002; @komarraju2008] entregan evidencia empírica a esta forma de entender el constructo: Mientras entre europeos-estadounidenses no existe relación significativa entre individualismo y colectivismo, la asociación si es observable entre afroamericanos [@komarraju2008]. Se debe recordar, además, que ya en los años 80, en su clásico *Habits of the Hearts*, Robert Bellah y su equipo describían dos tradiciones de individualismo en los Estados Unidos. En Chile, mediante un análisis de conglomerados a partir de la escala de Triandis (que distingue entre individualismo-colectivismo vertical y horizontal), se identificaron 5 grupos (colectivistas independientes, colectivistas puros, colectivistas idiocéntricos, individualistas alocéntricos y renegados) [@rojas2008]. Pensar en distintas modalidades de individualismo también permite dar una salida al problema del familiarismo identificado por Oyserman y colegas [-@oyserman2002]: No se trata de si el familiarismo es una característica propia del individualismo o del colectivismo, sino que hay individualismos que definen de forma diversa la relación de los individuos con sus familias.

De tal manera, lo que se desea resaltar aquí es la existencia de diversos perfiles de individualismo que emergen de distintas combinaciones de las dimensiones previamente mencionadas. Estos perfiles no solo difieren entre culturas, sino también dentro de una misma sociedad, como resultado de procesos de individualización divergentes que afectan de manera diferenciada distintos segmentos de la población.

La individualización es una corriente histórica y estructural que, entre sus efectos, transforma la relación de los individuos con la autoridad, así como los soportes y las modalidades que autorizan su ejercicio (Araujo, 2021). En algunos casos, estos procesos condujeron a modelos institucionales de individualismo, donde el individuo se convierte en un soberano que legitima un orden social liberal y democrático. Sin embargo, en otros casos, los resultados de los procesos de individualización pueden dar lugar a variantes de individualismo en las que los individuos podrían preferir formas de autoridad que se alejan del ideal representativo de la democracia.

En otras palabras, si es posible que el individualismo sea un elemento constituyente tanto de una democracia delegativa [@odonnell1994] como de una democracia representativa [@martuccelli2010], es por que cada una se sustenta en modelos de individualismo distintos. Es precisamente esta relación ambigua entre democracia e individualismo la que se busca poner en tensión en este marco analítico, y la que se examinará a través de la estrategia metodológica presentada a continuación.

[^1]: Notoriamente, la definición de individualismo de Hofstede incluye una mención a la familia. 
[^2]: Por ejemplo, partidos políticos, movimientos sociales o sindicatos. Pero, también, un matrimonio o un grupo de amigos.
