# Discusión

**Apoyo a la Democracia Delegativa**

Se constató que el respaldo a la democracia delegativa en la sociedad chilena se sitúa en niveles intermedios, siendo el apoyo a que los expertos tomen decisiones para el país ligeramente más elevado que el respaldo a un líder fuerte. Es relevante señalar que se han identificado algunas disparidades entre grupos, siendo especialmente destacable el menor apoyo hacia la democracia delegativa entre quienes identifican con la centro-derecha, en contraposición a lo esperado a partir de la experiencia nacional [@navia2019] e internacional [@donovan2021]. Otro aspecto relevante de este dato es que se observan diferencias entre la centro-derecha y las posiciones más extremas de derecha, las cuales sí exhiben un respaldo superior a la democracia delegativa. Una posible explicación para esto podría radicar en diferencias de ingresos o de nivel educativo, lo que se traduciría en un menor respaldo a la democracia delegativa entre las personas con posiciones más moderadas de derecha [@kang2018]. Esto plantea hipótesis interesantes acerca de cómo el estatus socioeconómico puede interactuar o moderar el efecto de la posición política en el respaldo a la democracia.

Resulta llamativo, además, que las zonas rurales y las ciudades con menos de 100 mil habitantes sean las que menos respaldan la democracia delegativa, dado que la evidencia ha apuntado a que las áreas rurales suelen mostrar un mayor apoyo a candidatos de derecha populista en países como Estados Unidos [@schafft2021] o Alemania [@deppisch2022]. Este hallazgo merece una mayor atención en investigaciones futuras que se propongan trazar una geografía del autoritarismo en Chile y explorar cómo este fenómeno puede mostrar diferencias entre zonas urbanas y rurales. 

**Perfiles de Individualismo**

El análisis de clases latentes realizado respalda la hipótesis de que los procesos de individualización divergen dentro de una misma sociedad. A partir de los datos examinados, se logró identificar cuatro perfiles distintos de individualismo en la sociedad chilena: individualismo autoritario, individualismo conservador, individualismo liberal e individualismo agéntico. Cada uno de estos perfiles equivale a variadas representaciones de la posición del individuo en la sociedad, y son resultado de combinaciones específicas de legitimidad de la acción individual en diferentes esferas, concepciones variadas del individuo, y diferentes valores e imperativos estructuralmente producidos. Además, la presencia de diferencias en edad, orientación política, ubicación geográfica o afiliación religiosa entre estos perfiles arroja luz sobre cómo los procesos estructurales interactúan de manera diferenciada con distintos segmentos de la población.

La tipología elaborada permite establecer un diálogo con la descripción del individualismo agéntico y el híper-actor relacional propuesto por Araujo y Martuccelli [-@araujo2020]. Este modelo presenta dos características fundamentales: en primer lugar, la confianza depositada en las habilidades personales para afrontar la vida social, y en segundo lugar, la centralidad de las redes interpersonales. Se observó que una de las clases identificadas se acerca de manera más nítida a este modelo, de ahí que se haya decidido mantener la denominación de "individualismo agéntico". No obstante, se debe destacar que los otros perfiles también exhiben rasgos que hacen suponer que comparten, al menos parcialmente, la descripción de Araujo y Martuccelli.

En relación con la confianza en el esfuerzo y las habilidades personales, esto podría observarse en la alta valoración de la competencia y los elevados niveles de independencia observados de manera transversal en todos los perfiles. En términos generales, los datos sugieren que la mayoría de los chilenos cree poseer las habilidades necesarias para asumir el control de sus propias vidas.

Uno de los perfiles identificados, el individualismo agéntico, parece llevar este rasgo hasta el extremo, ya que es el único en el cual se legitima el actuar estratégico. Estar en un *estado de alerta* para aprovechar las oportunidades es otra característica del individualismo agéntico descrita por Araujo y Martucceli [-@araujo2014]. En la sociedad chilena, la capacidad de aprovechar las oportunidades suele ser vista como un motivo de orgullo personal, aunque no sin contradicciones, especialmente cuando se convierte en transgresión. Se podría pensar que esta tipología refleja esa tensión: Mientras tres de las clases identificadas parecen percibir el oportunismo como un vicio colectivo, el individualismo agéntico lo celebra como un virtud personal.  

Por otro lado, el carácter relacional del individualismo chileno parece ser una característica que atraviesa todos los perfiles [@araujo2014]. Cierto es que se mide solo una identidad relacional (la familiar) y solo una identidad colectiva (la nacional). Pese a esto, no parece demasiado difícil argumentar la importancia de estas identidades y que incluirlas en el modelo sirve para un buen primer acercamiento.

También es importante señalar que el carácter relacional del individualismo chileno parece no entrar en contradicción con las concepciones independientes, que muestran niveles tan elevados como los indicadores de interdependencia. Esto es consistente tanto con las dos características que describen al individualismo agéntico [@araujo2020] como con las investigaciones sobre el *self-construal* en Chile [@benavides2020; @kolstad2009]. Además, ofrece más respaldo a la idea de que ubicar a Chile en un continuo entre el individualismo y el colectivismo resulta problemático. A pesar de que los chilenos mayoritariamente se identifican como individuos independientes, esto no se traduciría en la aceptación de ideales tipo *self-made man*. Por el contrario, la evidencia parece apuntar a que el individualismo chileno, en todas sus variantes, no se comprende de manera aislada de las identidades familiares y nacionales de las personas.

En resumen, a partir de los datos analizados, se puede concluir que el individualismo agéntico representa el modelo predominante de individualismo en Chile. Sin embargo, el aporte de esta investigación radica en que, mediante el análisis de clases latentes, es posible observar cómo este modelo diverge dentro de la sociedad chilena. Para algunos, la acción individual debe estar subordinada al orden normativo, mientras que para otros es legítimo actuar de manera estratégica incluso si ello transgrede normas sociales. Mientras que para unos la individualidad tiene cabida en todas las esferas, para otros su legitimidad no alcanza para la esfera afectiva. De tal modo, este enfoque permite observar los matices y las divergencias de los procesos de individualización en Chile. 

**Apoyo a la democracia delegativa y perfiles de individualismo**

El hecho de que haya sido posible establecer una relación estadísticamente significativa entre los perfiles de individualismo y el respaldo a la democracia delegativa debe ser considerado como una evidencia alentadora del potencial del modelo teórico de individualismo propuesto. Dos de los perfiles identificados muestran una asociación negativa con el apoyo a la democracia delegativa (el conservador y el liberal), mientras que los otros dos (el agéntico y el autoritario) presentan una relación positiva.

Cabe preguntarse si este no es un eje que permita distinguir entre los perfiles identificados: el individualismo conservador y el liberal podrían denominarse como *individualismos cívicos*, orientados hacia lo público. En contraste, el autoritario y el agéntico podrían considerarse más bien *hiperindividualismos*, que están orientados más bien hacia lo privado. En los primeros, la individualidad estaría vinculada a la pertenencia a una comunidad política; en los segundos, lo público representaría un desafío, un obstáculo que se debe evitar ya sea mediante la sumisión de la individualidad a un orden normativo (como en el caso del individualismo autoritario) o mediante la maximización de las habilidades personales (como es el caso del individualismo agéntico). 

La afinidad entre estos tipos de individualismo y la democracia delegativa podría explicarse debido a que esta variante de democracia permite a los ciudadanos ejercer el voto periódicamente (rendición de cuentas vertical) para luego retirarse de la esfera pública hasta la próxima elección [@peruzzotti2008]. Pero esta apatía está lejos de ser un cheque en blanco: a la autoridad electa se le exigen resultados, incluso si ello implica transgredir la autonomía de otras instituciones del Estado (rendición de cuentas horizontal). Si la relación entre los hiperindividualismos y la democracia delegativa se explica por una mayor apatía hacia el espacio público, como aquí se plantea, se esperaría encontrar diferencias entre los perfiles de individualismo en variables como la participación política o la confianza generalizada.

Aunque la distinción entre individualismos cívicos e hiperindividualismos puede recordar los constructos de individualismo horizontal e individualismo vertical, respectivamente, es necesario realizar algunas precisiones. En primer lugar, cabe señalar que el individualismo horizontal pone énfasis, sobre todo, en la unicidad del individuo. Aunque esto podría describir a los individualistas liberales, se debe notar que los individualistas conservadores no parecen estar tan dispuestos a aceptar esa unicidad en la esfera expresiva. Por otro lado, aunque se puede inferir que los hiperindividualismos muestran componentes jerárquicos, también es posible observar rasgos de individualismo horizontal, especialmente en el individualismo agéntico, como en la alta legitimidad de la individualidad expresiva. Lo que distingue a los individualismos cívicos de los hiperindividualismos no son tanto las visiones jerárquicas o sobre la unicidad del individuo, sino más bien su posición frente a la esfera pública. Sin embargo, en futuras investigaciones se debería profundizar en la relación entre el modelo teórico propuesto aquí y otras mediciones de individualismo, incluyendo las escalas de individualismo vertical y horizontal. 

Otro aspecto interesante que se debe destacar es que, mientras los individualistas autoritarios muestran un mayor respaldo a los líderes fuertes, los individualistas agénticos lo hacen a los expertos. Este hallazgo resulta relevante considerando que el individualismo agéntico, a diferencia del autoritario (pero en concordancia con el conservador y el liberal), exhibe altos niveles de apoyo a la individualidad en la esfera política. Esto podría indicar que lo que caracteriza al individualismo agéntico no sería tanto el autoritarismo, sino más bien una postura pragmática hacia la democracia. Este grupo podría valorar la democracia no necesariamente como un fin, sino como un medio que les permita resolver problemas privados.

# Conclusión

Si bien los niveles de apoyo a la democracia delegativa son, en promedio, moderados, esta investigación permite concluir que existen diferencias significativas en tal apoyo entre los distintos perfiles de individualismo identificados: el autoritario, el conservador, el liberal y el agéntico. Además, se propuso que estos cuatro perfiles podrían distribuirse a lo largo de un eje que distingue entre individualismos cívicos e hiperindividualismos.

El individualismo conservador y el liberal, categorizados como individualismos cívicos, muestran menores niveles de apoyo a la democracia delegativa. Estos perfiles tienden a valorar la individualidad en conexión con la comunidad política, lo que se traduciría en un mayor apoyo a los ideales más represantivos de democracia.

Por otro lado, el individualismo autoritario y el agéntico, que pueden ser entendidos como formas de hiperindividualismo, presentan un nivel de apoyo superior a la democracia delegativa. Estos perfiles se inclinan por una actitud de apatía hacia la esfera pública, lo que sugiere una valoración de la democracia más como un medio para fines personales que como un fin en sí mismo.

En resumen, esta investigación sugiere que la relación entre el individualismo y el apoyo a la democracia delegativa es significativa, pero divergente entre distintos grupos. Mientras que los individualismos cívicos parecen valorar una visión más representativa de la democracia, los hiperindividualismos favorecen un enfoque más pragmático y apático hacia la esfera pública. Esto ilustra un panorama general en el que las manifestaciones del individualismo, y su relación con otros fenómenos, aparecen como más complejas de lo que otros estudios han propuesto.

**Alcances, limitaciones y reflexiones finales**

A continuación, se presentarán algunas reflexiones sobre las limitaciones y posibles líneas de investigación futuras que se desprenden de este estudio. 

Para empezar, es importante reflexionar sobre las oportunidades que brinda el análisis de clases latentes en la investigación sobre los procesos de individualización en Chile. Dada la dificultad para traducir su marco teórico a una propuesta metodológica mediante las técnicas cuantitativas más comunes, la sociología del individuo se ha desarrollado principalmente desde una perspectiva cualitativa, resultando en descripciones profundas y estimulantes sobre el individuo en la sociedad chilena. Pese a ello, el enfoque metodológico adoptado en esta investigación permitió identificar algunos de los rasgos del individualismo agéntico descritos por Araujo y Martuccelli [-@araujo2014], al tiempo que ofrece una visión más matizada de cómo los procesos de individualización divergen en la sociedad chilena, diferenciándose entre grupos sociales y teniendo consecuencias en las actitudes políticas de los individuos. 

Por supuesto, enfoques cualitativos y cuantitativos no deben ser vistos como competitivos, sino como complementarios en el desarrollo de una sociología del individuo. Las propias conclusiones aquí delineadas, y las hipótesis que de ellas se desprenden, se verían fuertemente enriquecidas si se incluyeran datos cualitativos que permitirían obtener una compresión más profunda de las distintas variantes de individualismo y su relación divergente con la esfera pública. 

Ahora bien, es necesario reconocer las limitaciones que enfrentó esta investigación. La principal, posiblemente, se derive de los indicadores seleccionados. Aunque los resultados obtenidos parecen prometedores, es crucial continuar avanzando en la construcción y validación de indicadores que permitan traducir el modelo teórico aquí propuesto en un modelo de medición capaz de abordar el fenómeno del individualismo en Chile. En este sentido, hay cuatro puntos que vale la pena mencionar.

En primer lugar, es llamativo que no se observara una relación entre la valoración de la competencia y los indicadores de accionar estratégico, como evadir en el transporte público y mentir para obtener beneficios sociales. Se podría argumentar que estos representan dos dimensiones de un mismo constructo, el individualismo utilitario, con uno de ellos englobando la valoración de la competencia, el esfuerzo y la meritocracia, y el otro refiriéndose a los límites de esas conductas. Por ejemplo, una persona podría valorar la competencia entre individuos pero entender que ello implica el respeto común a ciertas normas;  mientras que otros, como sería el caso de los individualistas agénticos, podrían percibir que la competencia justifica un *todo vale*. Sin embargo, tampoco se puede descartar la posibilidad de que estos sean simplemente dos constructos diferentes. Sea cual sea el caso, es necesaria la elaboración y validación de indicadores que permitan medir el individualismo utilitario.

En segundo lugar, si los individualistas agénticos muestran una posición más pragmática frente a la democracia, ¿esto no debería reflejarse en una baja legitimidad del individualismo moral? El hecho de que los individualistas agénticos tengan una alta probabilidad de legitimar esa dimensión bien podría indicar que las razones para hacerlo no son necesaria o exclusivamente el individualismo. Otros factores, como la deseabilidad social, podrían estar sesgando estos resultados. Sin embargo, no es contradictorio que el individualismo agéntico legitime la individualidad en la esfera moral, especialmente si se vincula con los deseos de horizontalización del lazo social [@araujo2020a]. Preguntas que no aborden directamente la democracia, mediante temas tales como la pena de muerte o los derechos humanos, podrían mejorar la medición de este constructo.

En tercer lugar, como se ha mencionado anteriormente, hay razones para creer que la familia y la nación son particularmente relevantes a la hora de medir la interdependencia relacional y la identidad colectiva. No obstante, esto no significa que se deban descartar posibles diferencias en los perfiles identificados con respecto a otras identidades. Se podría hipotetizar, por ejemplo, que la identidad religiosa es más importante que la nacional entre los individualistas autoritarios, o que las amistades o las identidades profesionales pueden ser más relevantes, o bien complementar, la relevancia de la familia entre los individualistas liberales. Investigaciones futuras deberán abordar desde qué grupos de referencia los individuos construyen sus identidades.

Por último, la recodificación de variables continuas como dicotómicas es una solución pragmática, pero que no deja de ser problemática, ya que resulta en la pérdida de parte de la varianza de los ítems [@fernandes2019]. De tal modo, en el caso de construir indicadores originales a partir del modelo teórico de esta investigación, se debería considerar hacerlo directamente como variables categóricas que no necesiten recodificación para ser incluidas en el modelo de clases latentes. De esta manera, se obtendría claridad en los resultados sin sacrificar información ni poder estadístico.

Otras limitaciones provienen más bien de la muestra. Si 5 años ya se encuentra en el límite de lo que se puede considerar como datos relevantes para la actualidad, a esto se debe sumar que este último lustro ha sido uno particularmente tumultuoso: el Estallido Social, la Pandemia, el proceso constituyente, la crisis migratoria y la crisis de seguridad han sido algunos de los eventos de gran magnitud que han marcado la agenda durante los últimos años. ¿Están hoy los chilenos más dispuestos que hace 5 años a sacrificar su libertad y su individualidad en distintas esferas para obtener garantías de orden y seguridad? ¿Significó la emergencia sanitaria una transformación en como los expertos son percibidos y cuál debe ser su rol en la toma de decisiones? Entre las ollas comunes y los retiros de fondos previsionales, entre las protestas masivas y las cuarentenas, ¿cambiaron las concepciones -- independientes, relacionales y colectivas -- con las que los individuos construyen sus identidades? ¿Qué efectos puede tener la instauración del voto obligatorio en el eje individualismo cívico-hiperindividualismo, o en las percepciones de los ciudadanos sobre una democracia delegativa? Todas estas son preguntas relevantes que quedarán abiertas y deberán ser abordadas en el futuro. 

Por otro lado, no se puede descartar la presencia de sesgos de deseabilidad social o por casos perdidos. La Encuesta Mundial de Valores es un extenso cuestionario que, con más de 300 preguntas, aborda temas que pueden resultar sensibles para muchas personas. No se puede descartar, por lo tanto, que ciertos grupos de la población estén moderando -- o incluso ocultando -- sus percepciones sobre temas políticos o valóricos. Se identificó que las personas mayores de 60 años, sin educación universitaria, sin identificación política y los habitantes fuera de Santiago muestran mayores probabilidades de no responder en las variables clave de este estudio. Frente a esto, una posibilidad a considerar es la imputación de datos para cubrir esta brecha.

A su vez, dado que Chile ha participado en 6 olas de la Encuesta Mundial de Valores desde 1990, se debería considerar correr los modelos aquí propuestos utilizando datos de ediciones anteriores (así como estar atento a la próxima versión a realizarse entre 2023 y 2026). Esto permitiría evaluar si los resultados obtenidos en este estudio guardan consistencia con el pasado, así como observar la evolución de estos indicadores a lo largo del tiempo.

Pese a estas limitaciones, el trabajo contenido en este documento logra obtener resultados relevantes. Se encontró evidencia de que distintas formas de individualismo pueden generar actitudes políticas diferentes respecto a la democracia, el tipo de liderazgos esperados y el rol que los expertos deben desempeñar en la sociedad. Es importante considerar que estas inclinaciones no surgen en un vacío, sino que son el resultado de la interacción de factores institucionales y estructurales con la agencia de los individuos. De esta manera, se espera que la lectura de esta investigación provoque la reflexión en torno a los tipos de individuos que nuestras instituciones, a través de sus programas e incentivos, contribuyen a producir, así como en las consecuencias de estos procesos para la democracia chilena y la vida social en general. 


 
 
 
 

